Repository romiardanaputra/melancong-fe, pull requests merged in 2024-07, with the labels that each got.

#1 [DEV] feat: Add feature dashboard
  .eslintrc.json
  app/dashboard/user/page.tsx
  app/page.tsx
  components/ui/card.tsx
  components/ui/carousel.tsx
  package-lock.json
  package.json
Labels: enhancement

#2 [DEV] feat: Add feature dashboard
  app/dashboard/user/page.tsx
  app/page.tsx
  components/ui/card.tsx
  public/assets/images/carousel-1.webp
  public/assets/images/carousel-2.webp
Labels: enhancement

#4 Add Chatbot Feature
  app/api.ts
  app/chatbot/page.tsx
Labels: enhancement

#6 Feat/auth
  .eslintrc.json
  .husky/pre-commit
  app/(user)/auth/exForm/page.tsx
  app/(user)/auth/register/page.tsx
  app/(user)/auth/signIn/page.tsx
  app/layout.tsx
  app/page.tsx
  components/CustomField.tsx
  components/Logo.tsx
  components/SubmitButton.tsx
  components/form/LoginForm.tsx
  components/form/SignUpForm.tsx
  components/ui/form.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/select.tsx
  lib/actions/user.actions.ts
  lib/appwrite.config.ts
  lib/validation.ts
  package-lock.json
  package.json
  tailwind.config.ts
  tsconfig.json
  types/appwrite.types.ts
  types/index.d.ts
Labels: enhancement

#10 [DEV] Feature/destination (styling page)
  app/destinations/[id]/page.tsx
  app/home/page.tsx
  app/saved/page.tsx
  package-lock.json
Labels: documentation, enhancement

#22 [DEV]: Style/home
  app/(route)/home/_partials/Logo.tsx
  app/(route)/home/_partials/LogoIcon.tsx
  app/(route)/home/_partials/pages/dashboard/page.tsx
  app/(route)/home/page.tsx
  components/ui/navigation/SideBarAnimate.tsx
  data/index.tsx
  next.config.mjs
  package-lock.json
  package.json
Labels: enhancement

#21 [DEV] Feature/profile (styling)
  app/(route)/profile/edit/page.tsx
  app/(route)/profile/page.tsx
  package-lock.json
  package.json
Labels: documentation, enhancement

#27 [DEV] Fix/about
  app/(route)/dashboard/_partials/DashboardSidebar.tsx
  app/(route)/dashboard/_partials/Logo.tsx
  app/(route)/dashboard/_partials/LogoIcon.tsx
  app/(route)/dashboard/chatbot/page.tsx
  app/(route)/dashboard/layout.tsx
  app/(route)/landing/_partials/about/_partials/AboutList.tsx
  app/(route)/landing/_partials/about/_partials/ImageGrid.tsx
  app/(route)/landing/_partials/about/page.tsx
  app/(route)/landing/page.tsx
  app/globals.css
  components/ui/card/CardHoverEffect.tsx
  components/ui/card/CustomCard.tsx
  components/ui/footer/Footer.tsx
  components/ui/layout-grid.tsx
  components/ui/skeleton/SkeletonCard.tsx
  data/about-list.tsx
  data/card-grid.tsx
  data/index.ts
  data/index.tsx
  data/landing-link.tsx
  data/sidebar-link.tsx
Labels: enhancement

#28 [DEV] Fix/accessibility
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  app/(auth)/sign-up/page.tsx
  app/(route)/dashboard/_partials/Logo.tsx
  app/(route)/dashboard/_partials/LogoIcon.tsx
  app/(route)/dashboard/page.tsx
  app/(route)/dashboard/saved/page.tsx
  app/(route)/landing/_partials/about/page.tsx
  app/(route)/landing/_partials/hero-banner/page.tsx
  app/(route)/landing/_partials/recomendation/page.tsx
  components/ui/Filter.tsx
  components/ui/card/CardHoverEffect.tsx
  components/ui/card/CustomCard.tsx
  components/ui/form/Field.tsx
  components/ui/hero/ImageSlider.tsx
  components/ui/input/placeholders-and-vanish-input.tsx
  components/ui/navigation/SideBar.tsx
  components/ui/navigation/SideBarAnimate.tsx
  data/sidebar-link.tsx
  tailwind.config.ts
Labels: enhancement

#30 [DEV] Style/chatbot
  app/(route)/dashboard/chatbot/page.tsx
  app/(route)/dashboard/profile/edit/page.tsx
Labels: bug, documentation
